dynamixel_joint:
  controller:
    package: dynamixel_controllers
    module: joint_position_controller
    type: JointPositionController
  joint_name: dynamixel_joint
  joint_speed: 1.57
  motor:
    id: 4
    init: 2048
    min: 0
    max: 4095
